FROM debian:stretch

WORKDIR /home/script_dir

RUN apt-get update -y
RUN apt-get install -y build-essential make gawk git texinfo autoconf autopoint pkg-config gettext txt2man liblzma-dev libssl-dev libz-dev flex bison

ENV PATH="/home/script_dir/build-tools-gcc:${PATH}"

RUN git clone https://github.com/franzflasch/build-tools-gcc.git

WORKDIR /home/work_dir

RUN /bin/bash -c "/home/script_dir/build-tools-gcc/build-gcc -a arm -s gnu -v 8 -t && rm -rf /home/work_dir/*"
RUN /bin/bash -c "/home/script_dir/build-tools-gcc/build-gcc -a arm64 -s gnu -v 8 -t && rm -rf /home/work_dir/*"
RUN /bin/bash -c "/home/script_dir/build-tools-gcc/build-gcc -a x86 -s gnu -v 8 -t && rm -rf /home/work_dir/*"
RUN /bin/bash -c "/home/script_dir/build-tools-gcc/build-gcc -a x86_64 -s gnu -v 8 -t && rm -rf /home/work_dir/*"
RUN /bin/bash -c "/home/script_dir/build-tools-gcc/build-gcc -a cm4f -s gnu -v 8 -t && rm -rf /home/work_dir/*"
RUN /bin/bash -c "/home/script_dir/build-tools-gcc/build-gcc -a riscv-baremetal -s gnu -v 8 -t && rm -rf /home/work_dir/*"
