FROM debian:stretch

WORKDIR /home/work_dir

RUN apt-get update -y
RUN apt-get install -y build-essential make gawk git texinfo autoconf autopoint pkg-config gettext txt2man liblzma-dev libssl-dev libz-dev flex bison

ENV PATH="/home/work_dir/build-tools-gcc:${PATH}"

RUN git clone https://github.com/franzflasch/build-tools-gcc.git
RUN /bin/bash -c "/home/work_dir/build-tools-gcc/build -a arm -s gnu -v 8 -t"
