FROM debian:buster

ARG ARCH=""
ARG USE_TAR=""

WORKDIR /home/script_dir

RUN apt-get update -y
RUN apt-get install -y wget build-essential make gawk git subversion texinfo autoconf autopoint pkg-config gettext txt2man liblzma-dev libssl-dev libz-dev flex bison python3 python3-pip rsync
RUN pip3 install meson ninja

ENV PATH="/home/script_dir/build-tools-gcc:${PATH}"

ADD . /home/script_dir/build-tools-gcc

WORKDIR /home/work_dir

RUN /bin/bash -c "/home/script_dir/build-tools-gcc/build-gcc -a $ARCH -v 10 $USE_TAR && rm -rf /home/work_dir/*"
