FROM debian:bullseye

ARG ARCH=""
ARG USE_TAR=""
ARG PACKAGE=""

WORKDIR /home/script_dir

RUN apt-get update -y
RUN apt-get install -y wget build-essential make gawk git subversion texinfo autoconf autopoint pkg-config gettext txt2man liblzma-dev libssl-dev libz-dev flex bison python3 python3-pip rsync
RUN pip3 install meson ninja

ENV PATH="/home/script_dir/gcc-build-tools:${PATH}"

ADD . /home/script_dir/gcc-build-tools

WORKDIR /home/work_dir

RUN /bin/bash -c "/home/script_dir/gcc-build-tools/build-gcc -a $ARCH -v 11 $USE_TAR $PACKAGE"
RUN /bin/bash -c "mkdir /home/toolchain_install"
RUN /bin/bash -c "cp -rf /home/work_dir/*.xz /home/toolchain_install/ | true" # Continue, even if the file does not exist.

RUN /bin/bash -c "rm -rf /home/work_dir/*"
