# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: set env
        run: echo "BUILD_ARCH=$(basename $ARCH .yml)" >> $GITHUB_ENV
        env:
          ARCH: ${{ github.workflow }}
      - name: run_build_git
        run: ./tests/run_single_test.sh $BUILD_ARCH

      # do not package as needs to much memory for github actions
      #- name: ${BUILD_ARCH}_git_artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: toolchain_built_from_git
      #    path: toolchain_install
      - name: run_build_tar
        run: ./tests/run_single_test.sh $BUILD_ARCH "-t"
      #- name: ${BUILD_ARCH}_tar_artifact
      #  uses: actions/upload-artifact@v2
      #  with:
      #    name: toolchain_built_from_tar
      #    path: toolchain_install

